### ISSUE TITLE
Decode Errorが出ました

### ISSUE THREAD

**Issue by yuto-tsuji** [tmori/athrill-target#1]
-- Error --
Powered by TOPPERS/HRP2 RTOS
Initialization is completed..
System logging task is started on port 3.
Decode Error
CPU(pc=0x180106e0) Exception!!
-- objdump --
180106e0:       e15b10fa        ldrsh   r1, [fp, #-10]
180106e4:       e3063667        movw    r3, #26215      ; 0x6667
180106e8:       e3463666        movt    r3, #26214      ; 0x6666
180106ec:       e0c32391        smull   r2, r3, r1, r3

**Comment by tmori** [comment]
報告ありがとうございます！
デコードエラー発生原因は，ldrsh命令が未実装であったためでした．
以下で修正済みです．

https://github.com/tmori/athrill-target/commit/d22985a751ad7cc39880460c5e1026d02eedf170

```
instruction: arm_ldrsh_imm_a1

cond: 14, 0xe, 0b1110
P: 1, 0x1, 0b1
U: 0, 0x0, 0b0
W: 0, 0x0, 0b0
Rn: 11, 0xb, 0b1011
Rt: 1, 0x1, 0b1
imm8: 10, 0xa, 0b1010
```
