### ISSUE TITLE
Decode Errorが出ました

### ISSUE THREAD

**Issue by yuto-tsuji** [tmori/athrill-target#2]
-- Error --
Powered by TOPPERS/HRP2 RTOS
Initialization is completed..
System logging task is started on port 3.
Decode Error
CPU(pc=0x18005330) Exception!!

-- objdump --
18005330:       e2233001        eor     r3, r3, # 1
18005334:       e6ef3073        uxtb    r3, r3
18005338:       e3530000        cmp     r3, #0
1800533c:       0a000013        beq     18005390 <get_nextaction+0x200>
18005340:       e3043044        movw    r3, #16452      ; 0x4044

**Comment by tmori** [comment]
ご連絡ありがとうございます．
以下で修正させて頂きました．m(_ _)m

https://github.com/tmori/athrill-target/commit/8ece14bff8fed633aa96944c0ff6d6a94c131944
