### ISSUE TITLE
ETロボコンシミュレータ向け時刻同期用パラメータの追加

### ISSUE THREAD

**Issue by tmori** [tmori/athrill-target#3]
現状，athrillからUnityに送信する時刻同期およびアクチュエータ情報の通知タイミングはEV3RTからAPI呼び出しを契機としている．

EV3RT側の変更があった場合，時刻同期タイミングが変わってしまうため，athrill側で時刻同期タイミングを調整できるようにすべきと考えている．

**Comment by takasehideki** [comment]
下記に移行
https://github.com/toppers/athrill-target-v850e2m/issues/1
