### ISSUE TITLE
ETロボコン向けシミュレータ時刻同期周りのスレッド競合の可能性

### ISSUE THREAD

**Issue by tmori** [tmori/athrill-target#4]
Unityからの時刻同期およびセンシング情報は，athrill内のスレッドでUDPパケット受信し，そのデータをレジスタ用のバッファにコピーしている．

このUDPスレッドは，CPU駆動で実行するスレッドと排他していないので，競合する可能性がある．修正方法は単純で，これらのスレッド間で共有データアクセスする際に排他をかければよい．

**Comment by takasehideki** [comment]
下記に移行
https://github.com/toppers/athrill-target-v850e2m/issues/2
